server:
  host: "0.0.0.0"
  port: 8080

rtmp:
  port: 1935
  buffer_size: 4096
  max_streams: 100
  stream_path: "/live"
  record_path: "./recordings"
  enable_hls: true
  hls_path: "./hls"
  segment_time: 10

logging:
  level: "debug"
  format: "json"
  file: ""

security:
  enable_auth: true
  api_key: "paitec_secure_key_2024"
  allowed_ips: []
  web_auth:
    username: "admin"
    password: "paitec123"
    session_timeout: 3600  # 1 hour 